COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://Shpot:Taranchila322@db-4server.mysql.database.azure.com/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://Shpot:Taranchila322@db-4server.mysql.database.azure.com/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: root
